// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bwoodworthIBLX/demo_contacts/pkg/pb/service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/bwoodworthIBLX/demo_contacts/pkg/pb/service.proto

It has these top-level messages:
	VersionResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DemoContacts service

type DemoContactsClient interface {
	GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type demoContactsClient struct {
	cc *grpc.ClientConn
}

func NewDemoContactsClient(cc *grpc.ClientConn) DemoContactsClient {
	return &demoContactsClient{cc}
}

func (c *demoContactsClient) GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/service.DemoContacts/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DemoContacts service

type DemoContactsServer interface {
	GetVersion(context.Context, *google_protobuf.Empty) (*VersionResponse, error)
}

func RegisterDemoContactsServer(s *grpc.Server, srv DemoContactsServer) {
	s.RegisterService(&_DemoContacts_serviceDesc, srv)
}

func _DemoContacts_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoContactsServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.DemoContacts/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoContactsServer).GetVersion(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DemoContacts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.DemoContacts",
	HandlerType: (*DemoContactsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _DemoContacts_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/bwoodworthIBLX/demo_contacts/pkg/pb/service.proto",
}

func init() {
	proto.RegisterFile("github.com/bwoodworthIBLX/demo_contacts/pkg/pb/service.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x55, 0x06, 0x0a, 0x16, 0x12, 0x28, 0x03, 0xaa, 0x02, 0x03, 0xea, 0x84, 0x04, 0xb5,
	0x05, 0xdd, 0x28, 0x53, 0x01, 0x21, 0x24, 0x06, 0xd4, 0x01, 0x21, 0x16, 0xb0, 0x93, 0x8b, 0x6b,
	0x91, 0xf8, 0x2c, 0xdb, 0x4d, 0xe8, 0xca, 0x2b, 0xf0, 0x68, 0xbc, 0x02, 0x0f, 0x82, 0x9a, 0x38,
	0x28, 0x02, 0x16, 0xb6, 0xfc, 0x77, 0xf7, 0xff, 0x5f, 0xf4, 0x9b, 0x9c, 0x4b, 0xe5, 0xe7, 0x0b,
	0x41, 0x13, 0x2c, 0x98, 0xa8, 0x10, 0xd3, 0x0a, 0xad, 0x9f, 0xdf, 0x4c, 0x6f, 0x1f, 0x58, 0x0a,
	0x05, 0x3e, 0x25, 0xa8, 0x3d, 0x4f, 0xbc, 0x63, 0xe6, 0x45, 0x32, 0x23, 0x98, 0x03, 0x5b, 0xaa,
	0x04, 0xa8, 0xb1, 0xe8, 0x31, 0xea, 0x07, 0x19, 0xef, 0x49, 0x44, 0x99, 0x03, 0xab, 0xc7, 0x62,
	0x91, 0x31, 0x28, 0x8c, 0x5f, 0x36, 0x57, 0xf1, 0x7e, 0x58, 0x72, 0xa3, 0x18, 0xd7, 0x1a, 0x3d,
	0xf7, 0x0a, 0xb5, 0x0b, 0xdb, 0x49, 0xe7, 0x0f, 0xf2, 0x65, 0xe6, 0x9b, 0x8c, 0x64, 0x24, 0x41,
	0x8f, 0x4a, 0x9e, 0xab, 0x94, 0x7b, 0x60, 0xbf, 0x3e, 0x82, 0xf9, 0xb8, 0x73, 0xec, 0x2a, 0x2e,
	0x25, 0x58, 0x86, 0xa6, 0x8e, 0xff, 0x03, 0x75, 0xd6, 0x41, 0x29, 0x9d, 0xa1, 0xc8, 0xf1, 0x15,
	0x0d, 0xe8, 0x2e, 0x52, 0xa2, 0x2d, 0xbe, 0x23, 0x56, 0xa2, 0xf1, 0x0e, 0x8f, 0xc8, 0xf6, 0x3d,
	0x58, 0xa7, 0x50, 0xcf, 0xc0, 0x19, 0xd4, 0x0e, 0xa2, 0x01, 0xe9, 0x97, 0xcd, 0x68, 0xd0, 0x3b,
	0xe8, 0x1d, 0x6e, 0xce, 0x5a, 0x79, 0xfa, 0x4c, 0xb6, 0x2e, 0xa1, 0xc0, 0x8b, 0x50, 0x5e, 0x74,
	0x47, 0xc8, 0x35, 0xf8, 0xe0, 0x8f, 0x76, 0x69, 0x53, 0x08, 0x6d, 0xdb, 0xa2, 0x57, 0xab, 0xb6,
	0xe2, 0x01, 0x6d, 0xdb, 0xfd, 0x41, 0x1a, 0xee, 0xbc, 0x7d, 0x7c, 0xbe, 0xaf, 0x91, 0x68, 0x83,
	0x05, 0xc2, 0x74, 0xfc, 0x78, 0xf2, 0xbf, 0x97, 0x9b, 0x18, 0x21, 0xd6, 0x6b, 0xe0, 0xf8, 0x2b,
	0x00, 0x00, 0xff, 0xff, 0x38, 0x55, 0xf8, 0xe8, 0xf5, 0x01, 0x00, 0x00,
}
